"""
漏洞类型知识模块

包含各种漏洞类型的专业知识
"""

from .injection import SQL_INJECTION, NOSQL_INJECTION, COMMAND_INJECTION, CODE_INJECTION
from .xss import XSS_REFLECTED, XSS_STORED, XSS_DOM
from .auth import AUTH_BYPASS, IDOR, BROKEN_ACCESS_CONTROL
from .crypto import WEAK_CRYPTO, HARDCODED_SECRETS
from .ssrf import SSRF
from .deserialization import INSECURE_DESERIALIZATION
from .path_traversal import PATH_TRAVERSAL
from .xxe import XXE
from .race_condition import RACE_CONDITION
from .csrf import CSRF
from .business_logic import BUSINESS_LOGIC, RATE_LIMITING
from .open_redirect import OPEN_REDIRECT
from .solidity import (
    SOLIDITY_REENTRANCY,
    SOLIDITY_INTEGER_OVERFLOW,
    SOLIDITY_ACCESS_CONTROL,
    SOLIDITY_ORACLE_MANIPULATION,
    SOLIDITY_SIGNATURE_REPLAY,
    SOLIDITY_SIGNATURE_MALLEABILITY,
    SOLIDITY_PROXY_SECURITY,
    SOLIDITY_PRECISION_LOSS,
    SOLIDITY_FRONT_RUNNING,
    SOLIDITY_CROSSCHAIN_SECURITY,
    SOLIDITY_ERC20_SAFETY,
    SOLIDITY_AMM_SECURITY,
    SOLIDITY_LENDING_SECURITY,
    SOLIDITY_DEFI_DOS,
    SOLIDITY_GOVERNANCE_SECURITY,
    SOLIDITY_NFT_SECURITY,
    SOLIDITY_STAKING_SECURITY,
    SOLIDITY_MULTISIG_SECURITY,
)

# 所有漏洞知识文档
ALL_VULNERABILITY_DOCS = [
    # 注入类
    SQL_INJECTION,
    NOSQL_INJECTION,
    COMMAND_INJECTION,
    CODE_INJECTION,
    # XSS类
    XSS_REFLECTED,
    XSS_STORED,
    XSS_DOM,
    # 认证授权类
    AUTH_BYPASS,
    IDOR,
    BROKEN_ACCESS_CONTROL,
    # 加密类
    WEAK_CRYPTO,
    HARDCODED_SECRETS,
    # 请求伪造
    CSRF,
    SSRF,
    # 其他
    INSECURE_DESERIALIZATION,
    PATH_TRAVERSAL,
    XXE,
    RACE_CONDITION,
    BUSINESS_LOGIC,
    RATE_LIMITING,
    OPEN_REDIRECT,
    # Solidity / 智能合约
    SOLIDITY_REENTRANCY,
    SOLIDITY_INTEGER_OVERFLOW,
    SOLIDITY_ACCESS_CONTROL,
    SOLIDITY_ORACLE_MANIPULATION,
    SOLIDITY_SIGNATURE_REPLAY,
    SOLIDITY_SIGNATURE_MALLEABILITY,
    SOLIDITY_PROXY_SECURITY,
    SOLIDITY_PRECISION_LOSS,
    SOLIDITY_FRONT_RUNNING,
    SOLIDITY_CROSSCHAIN_SECURITY,
    SOLIDITY_ERC20_SAFETY,
    SOLIDITY_AMM_SECURITY,
    SOLIDITY_LENDING_SECURITY,
    # Solidity 业务逻辑
    SOLIDITY_DEFI_DOS,
    SOLIDITY_GOVERNANCE_SECURITY,
    SOLIDITY_NFT_SECURITY,
    SOLIDITY_STAKING_SECURITY,
    SOLIDITY_MULTISIG_SECURITY,
]

__all__ = [
    "ALL_VULNERABILITY_DOCS",
    # 注入类
    "SQL_INJECTION",
    "NOSQL_INJECTION", 
    "COMMAND_INJECTION",
    "CODE_INJECTION",
    # XSS类
    "XSS_REFLECTED",
    "XSS_STORED",
    "XSS_DOM",
    # 认证授权类
    "AUTH_BYPASS",
    "IDOR",
    "BROKEN_ACCESS_CONTROL",
    # 加密类
    "WEAK_CRYPTO",
    "HARDCODED_SECRETS",
    # 请求伪造
    "CSRF",
    "SSRF",
    # 其他
    "INSECURE_DESERIALIZATION",
    "PATH_TRAVERSAL",
    "XXE",
    "RACE_CONDITION",
    "BUSINESS_LOGIC",
    "RATE_LIMITING",
    "OPEN_REDIRECT",
    # Solidity / 智能合约
    "SOLIDITY_REENTRANCY",
    "SOLIDITY_INTEGER_OVERFLOW",
    "SOLIDITY_ACCESS_CONTROL",
    "SOLIDITY_ORACLE_MANIPULATION",
    "SOLIDITY_SIGNATURE_REPLAY",
    "SOLIDITY_SIGNATURE_MALLEABILITY",
    "SOLIDITY_PROXY_SECURITY",
    "SOLIDITY_PRECISION_LOSS",
    "SOLIDITY_FRONT_RUNNING",
    "SOLIDITY_CROSSCHAIN_SECURITY",
    "SOLIDITY_ERC20_SAFETY",
    "SOLIDITY_AMM_SECURITY",
    "SOLIDITY_LENDING_SECURITY",
    # Solidity 业务逻辑
    "SOLIDITY_DEFI_DOS",
    "SOLIDITY_GOVERNANCE_SECURITY",
    "SOLIDITY_NFT_SECURITY",
    "SOLIDITY_STAKING_SECURITY",
    "SOLIDITY_MULTISIG_SECURITY",
]

